import sodium from 'libsodium-wrappers-sumo';
import { initCrypto } from './sodium-init';
import { hkdf } from './hkdf';
import { AEAD_KEY_LENGTH, AEAD_NONCE_LENGTH, VAULT_KEY_INFO } from './constants';

export interface VaultData {
  pgpPrivateKeyArmored: string;
  identityKeyPair: {
    publicKey: string; // base64
    privateKey: string; // base64
  };
  keyBundleExport: string; // JSON stringified key bundle
  ratchetSessions: Record<string, string>; // contactId -> JSON stringified ratchet state
  deviceId: string;
  recoveryCodeHash: string;
  createdAt: number;
  version: number;
}

interface EncryptedVault {
  nonce: string; // base64
  salt: string; // base64
  ciphertext: string; // base64
  version: number;
}

/**
 * Local encrypted vault for storing all sensitive key material.
 *
 * Architecture:
 *
 * During SETUP:
 *   1. User registers a WebAuthn passkey → we get a stable credentialId
 *   2. Generate a random 32-byte vault key (VK)
 *   3. Generate a random 32-byte wrapping salt (WS)
 *   4. Derive wrapping key: WK = HKDF(ikm=credentialId, salt=WS, info="vault-wrap", 32)
 *   5. Encrypt VK with WK: wrapped_vk = AEAD_Encrypt(WK, VK)
 *   6. Store in localStorage: { wrapping_salt, wrapped_vk, credential_id }
 *   7. Use VK to encrypt the vault data
 *
 * During UNLOCK:
 *   1. User asserts WebAuthn passkey → biometric/PIN check succeeds
 *      The assertion proves the user is present. We DON'T derive keys from
 *      the signature (it changes every time due to different challenges).
 *   2. Retrieve credentialId and wrapping salt from localStorage
 *   3. Re-derive: WK = HKDF(ikm=credentialId, salt=WS, info="vault-wrap", 32)
 *   4. Unwrap VK using WK
 *   5. Decrypt vault data using VK
 *
 * Why credentialId is acceptable as IKM:
 * - It's a random value generated by the authenticator (typically 32-64 bytes)
 * - It's unique per credential and stable across assertions
 * - Combined with the wrapping salt via HKDF, it produces a strong key
 * - Physical access to the device + knowledge of credentialId is required
 * - WebAuthn assertion still gates access (attacker can't skip biometric)
 *
 * For RECOVERY (all devices lost):
 *   1. User provides PGP private key + recovery code
 *   2. Recovery key = HKDF(ikm=recovery_code_bytes, salt=recovery_salt, info="vault-recovery", 32)
 *   3. A second wrapped copy of VK is stored encrypted with the recovery key
 *
 * Stored in localStorage:
 *   - e2ee_vault: AEAD-encrypted vault data blob
 *   - e2ee_wrapping_salt: random salt for wrapping key derivation
 *   - e2ee_wrapped_vk: vault key encrypted with wrapping key
 *   - e2ee_credential_id: WebAuthn credential ID
 *   - e2ee_recovery_wrapped_vk: vault key encrypted with recovery-derived key
 *   - e2ee_recovery_salt: salt for recovery key derivation
 */
export class LocalVault {
  private vaultKey: Uint8Array | null = null;

  /**
   * Generate a new random vault key. Called during initial setup.
   */
  async generateVaultKey(): Promise<Uint8Array> {
    const s = await initCrypto();
    this.vaultKey = s.randombytes_buf(AEAD_KEY_LENGTH);
    return new Uint8Array(this.vaultKey);
  }

  /**
   * Derive a wrapping key from stable WebAuthn credential ID and a salt.
   *
   * The credentialId is stable across assertions (unlike the signature).
   * Combined with HKDF and a random salt, this produces a strong wrapping key.
   */
  async deriveWrappingKey(
    credentialId: Uint8Array,
    wrappingSalt: Uint8Array
  ): Promise<Uint8Array> {
    const s = await initCrypto();
    const info = new TextEncoder().encode(VAULT_KEY_INFO + '-wrap');
    return hkdf(s, credentialId, wrappingSalt, info, AEAD_KEY_LENGTH);
  }

  /**
   * Wrap (encrypt) the vault key for persistent storage.
   *
   * @param wrappingKey Key derived from credentialId + salt
   * @returns Encrypted vault key blob (nonce + ciphertext, base64)
   */
  async wrapVaultKey(wrappingKey: Uint8Array): Promise<{ nonce: string; ciphertext: string }> {
    const s = await initCrypto();
    if (!this.vaultKey) throw new Error('No vault key to wrap');

    const nonce = s.randombytes_buf(AEAD_NONCE_LENGTH);
    const ciphertext = s.crypto_aead_xchacha20poly1305_ietf_encrypt(
      this.vaultKey,
      null,
      null,
      nonce,
      wrappingKey
    );

    return {
      nonce: Buffer.from(nonce).toString('base64'),
      ciphertext: Buffer.from(ciphertext).toString('base64'),
    };
  }

  /**
   * Unwrap (decrypt) the vault key using the wrapping key.
   *
   * @param wrappingKey Key derived from credentialId + salt
   * @param wrappedKey The stored encrypted vault key blob
   */
  async unwrapVaultKey(
    wrappingKey: Uint8Array,
    wrappedKey: { nonce: string; ciphertext: string }
  ): Promise<void> {
    const s = await initCrypto();
    const nonce = Uint8Array.from(Buffer.from(wrappedKey.nonce, 'base64'));
    const ciphertext = Uint8Array.from(Buffer.from(wrappedKey.ciphertext, 'base64'));

    this.vaultKey = s.crypto_aead_xchacha20poly1305_ietf_decrypt(
      null,
      ciphertext,
      null,
      nonce,
      wrappingKey
    );
  }

  /**
   * Derive a recovery wrapping key from recovery code bytes and salt.
   * Used to create a second wrapped copy of the vault key for recovery.
   */
  async deriveRecoveryWrappingKey(
    recoveryCodeBytes: Uint8Array,
    recoverySalt: Uint8Array
  ): Promise<Uint8Array> {
    const s = await initCrypto();
    const info = new TextEncoder().encode(VAULT_KEY_INFO + '-recovery');
    return hkdf(s, recoveryCodeBytes, recoverySalt, info, AEAD_KEY_LENGTH);
  }

  /**
   * Set vault key directly (for testing or when vault key is known).
   */
  setVaultKey(key: Uint8Array): void {
    this.vaultKey = new Uint8Array(key);
  }

  /**
   * Encrypt vault data for local storage.
   * Uses per-encryption salt to derive unique encryption key from vault key.
   */
  async encrypt(data: VaultData): Promise<string> {
    const s = await initCrypto();
    if (!this.vaultKey) throw new Error('Vault is locked');

    const plaintext = new TextEncoder().encode(JSON.stringify(data));
    const nonce = s.randombytes_buf(AEAD_NONCE_LENGTH);
    const salt = s.randombytes_buf(32);

    // Derive per-encryption key: HKDF(ikm=vaultKey, salt=salt, info="vault-enc", 32)
    const info = new TextEncoder().encode(VAULT_KEY_INFO + '-enc');
    const encKey = hkdf(s, this.vaultKey, salt, info, AEAD_KEY_LENGTH);

    const ciphertext = s.crypto_aead_xchacha20poly1305_ietf_encrypt(
      plaintext,
      salt, // bind salt as additional data
      null,
      nonce,
      encKey
    );

    encKey.fill(0);
    plaintext.fill(0);

    const vault: EncryptedVault = {
      nonce: Buffer.from(nonce).toString('base64'),
      salt: Buffer.from(salt).toString('base64'),
      ciphertext: Buffer.from(ciphertext).toString('base64'),
      version: 1,
    };

    return JSON.stringify(vault);
  }

  /**
   * Decrypt vault data from local storage.
   */
  async decrypt(encryptedJson: string): Promise<VaultData> {
    const s = await initCrypto();
    if (!this.vaultKey) throw new Error('Vault is locked');

    const vault: EncryptedVault = JSON.parse(encryptedJson);
    const nonce = Uint8Array.from(Buffer.from(vault.nonce, 'base64'));
    const salt = Uint8Array.from(Buffer.from(vault.salt, 'base64'));
    const ciphertext = Uint8Array.from(Buffer.from(vault.ciphertext, 'base64'));

    const info = new TextEncoder().encode(VAULT_KEY_INFO + '-enc');
    const encKey = hkdf(s, this.vaultKey, salt, info, AEAD_KEY_LENGTH);

    const plaintext = s.crypto_aead_xchacha20poly1305_ietf_decrypt(
      null,
      ciphertext,
      salt,
      nonce,
      encKey
    );

    encKey.fill(0);

    const data: VaultData = JSON.parse(new TextDecoder().decode(plaintext));
    return data;
  }

  /**
   * Check if vault is unlocked.
   */
  isUnlocked(): boolean {
    return this.vaultKey !== null;
  }

  /**
   * Lock the vault, clearing the vault key from memory.
   */
  lock(): void {
    if (this.vaultKey) {
      this.vaultKey.fill(0);
      this.vaultKey = null;
    }
  }

  /**
   * Securely wipe all vault data from storage.
   */
  static wipeStorage(): void {
    if (typeof localStorage !== 'undefined') {
      localStorage.removeItem('e2ee_vault');
      localStorage.removeItem('e2ee_wrapping_salt');
      localStorage.removeItem('e2ee_wrapped_vk');
      localStorage.removeItem('e2ee_credential_id');
      localStorage.removeItem('e2ee_recovery_wrapped_vk');
      localStorage.removeItem('e2ee_recovery_salt');
      localStorage.removeItem('e2ee_identity');
    }
    if (typeof indexedDB !== 'undefined') {
      indexedDB.deleteDatabase('e2ee-messenger');
    }
  }
}
